name: ci
on:
  push:
    branches:
      - PE-temp
permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Configure Git Credentials
        run: |
          git config --global user.email "virajsalaka@gmail.com"
          git config --global user.name "VirajSalaka" 
      - uses: actions/setup-python@v5
        with:
          python-version: 3.12
      - run: echo "cache_id=$(date --utc '+%V')" >> $GITHUB_ENV
      - uses: actions/cache@v4
        with:
          key: mkdocs-material-${{ env.cache_id }}
          path: .cache
          restore-keys: |
            mkdocs-material-
      - run: |
          echo "Installing Python dependencies"
          pip install --upgrade pip  # Ensure pip is up-to-date
          pip install zipp==3.0.0
          pip install pathlib2==2.3.5
          pip install -U --upgrade mkdocs==1.4.2
          pip install Pygments==2.14.0
          pip install pymdown-extensions==9.10
          pip install mkdocs-minify-plugin==0.6.2
          pip install mkdocs-markdownextradata-plugin==0.2.5
          pip install mkdocs-redirects==1.2.0
          pip install pathlib==1.0.1
          pip install -U mkdocs-material==9.1.2
          pip install markdown-include==0.8.1
          pip install markdown==3.2.1
          pip install mkdocs-exclude==1.0.2
          pip install -U Jinja2==3.1.0
          pip install mkdocs-glightbox==0.3.4
          pip install mkdocs-include-markdown-plugin==1.0.0
          pip install mkdocs-open-in-new-tab==1.0.3
      - name: Build site developer
        run: mkdocs build --config-file en/developer-docs/mkdocs.yml
      - name: Build site
        run: mkdocs build --config-file en/pe-docs/mkdocs.yml 
      - name: Move site developer to tempDir
        run: |
          mv en/developer-docs/site/developer /tmp/developer
      - name: Move site platform-engineer to tempDir
        run: |
          cp -r en/developer-docs/site/platform-engineer /tmp/platform-engineer    
      - name: Deploy to gh-pages-dev-2 subdirectory
        run: |
          git fetch origin gh-pages-dev-2 || git checkout --orphan gh-pages-dev-2
          git checkout gh-pages-dev-2
          rm -rf developer  # Clear existing directory if needed
          mkdir -p developer
          cp -r /tmp/developer/* developer/
          git add developer/
          git commit -m "Deploy to product1 directory"
          git push origin gh-pages-dev-2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}    
      - name: Deploy to gh-pages-dev-2 subdirectory
        run: |
          rm -rf platform-engineer  # Clear existing directory if needed
          mkdir -p platform-engineer
          cp -r /tmp/platform-engineer/* platform-engineer/
          git add platform-engineer/
          git commit -m "Deploy to platform-engineer directory"
          git push origin gh-pages-dev-2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}           
